name: Upgrade CoreLox in Playground

on:
  repository_dispatch:
    types: [corelox-release]

jobs:
  fetch_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Playground
        uses: actions/checkout@v3

      - name: Download Corelox WASM from Release
        uses: dawidd6/github-release-download@v2
        with:
          repository: "mvishiu11/CoreLox"
          tag: latest
          token: ${{ secrets.GH_TOKEN }}
          pattern: "corelox.*"
          overwrite: true

      - name: Show downloaded files
        run: ls -la

      - name: Move WASM files
        run: |
          mkdir -p public/wasm
          mv corelox.wasm corelox.mjs public/wasm/ || true

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Update CoreLox WASM from release ${{ github.event.client_payload.release_tag }}" || echo "No changes to commit"
      - name: Push changes
        run: git push

    #   - name: Deploy
    #     run: |
    #       npm install
    #       npm run build
    #       npm run deploy
    #     env:
    #       VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
